### ISSUE TITLE
Request: Convert existing images

### ISSUE THREAD

**Issue by Eaglef90** [Fric-88/Badgernet.Umbraco.WebPicAuto#2]
Hello and thank you for your add-in for Umbraco. I just came across it; it is very nice and handy. I would like to make a feature request though. Currently, it only resizes/converts files on upload. It would be nice if there were some way to resize/convert existing files so users don't have to go back and delete then reupload and reinsert images on existing content. Thank you.

**Comment by Fric-88** [comment]
Hi, im glad that u find the package useful. 
You suggeston makes sense, will look into it. Thank for you feedback.

**Comment by Fric-88** [comment]
Version 1.1.3 now lets you convert and resize existing images.
