### ISSUE TITLE
Umbraco v14

### ISSUE THREAD

**Issue by Lordchapter** [Fric-88/Badgernet.Umbraco.WebPicAuto#7]
When trying to update my project from v13.3.2 to v14 I get the following error:

Detected package version outside of dependency constraint: Badgernet.Umbraco.WebPicAuto 1.1.3 requires Umbraco.Cms (>= 13.0.0 && < 14.0.0) but version Umbraco.Cms 14.0.0 was resolved.

Will WebPicAuto be compatible with v14 soon?

Thanks!

**Comment by Fric-88** [comment]
Hi, yes, i am working on a new version for Umbraco 14. I cant really say when it will be available since i am building it from scratch (at least the frontend part), because of the new backoffice in Umbraco 14.

**Comment by Lordchapter** [comment]
Awesome! Thanks for the feedback!

**Comment by Fric-88** [comment]
@Lordchapter If you are still interested, you can check out the new version that works with Umbraco 14 & 15  [here](https://github.com/Fric-88/Badgernet.Umbraco.MediaTools).
